CREATE DATABASE eventdb;
GO
USE eventdb;
GO
CREATE TABLE users (id VARCHAR(50) PRIMARY KEY, name VARCHAR(100), email VARCHAR(100));
CREATE TABLE orders (id VARCHAR(50) PRIMARY KEY, userId VARCHAR(50), amount FLOAT);
CREATE TABLE payments (id VARCHAR(50) PRIMARY KEY, orderId VARCHAR(50), status VARCHAR(50));
CREATE TABLE inventory (sku VARCHAR(50) PRIMARY KEY, qty INT);
